[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#61f7b1"
backgroundColor = "#020604"
secondaryBackgroundColor = "#07100b"
textColor = "#eafff3"
