"""
Real PDF report using reportlab.
Falls back to a valid minimal-stub PDF if reportlab is missing.

Public API used by app.py:
    generate_report(input_path, verdict, sha256, phash) -> bytes
"""
from __future__ import annotations
import io, os, datetime
from typing import Any


def generate_report(input_path: str, verdict: dict,
                    sha256: str, phash: str) -> bytes:
    try:
        return _real_report(input_path, verdict, sha256, phash)
    except Exception as e:
        return _stub_pdf(f"report generation failed: {e}")


def _real_report(input_path: str, verdict: dict,
                 sha256: str, phash: str) -> bytes:
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                     Table, TableStyle, PageBreak, Image as RLImage)
    from reportlab.pdfgen import canvas as rlcanvas

    buf = io.BytesIO()
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="H", fontSize=18, spaceAfter=8,
                              textColor=colors.HexColor("#1e3a8a"),
                              fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="SubH", fontSize=13, spaceBefore=14, spaceAfter=6,
                              textColor=colors.HexColor("#1e3a8a"),
                              fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="Verdict", fontSize=22, alignment=1,
                              fontName="Helvetica-Bold", spaceAfter=10))
    styles.add(ParagraphStyle(name="Small", fontSize=8,
                              textColor=colors.grey))

    doc = SimpleDocTemplate(buf, pagesize=LETTER,
                            leftMargin=0.7 * inch, rightMargin=0.7 * inch,
                            topMargin=0.6 * inch, bottomMargin=0.6 * inch,
                            title="Evidence Analysis Report")

    story = []

    # ---- Header ----
    story.append(Paragraph("Digital Evidence Analysis Report", styles["H"]))
    story.append(Paragraph("Generated by DeepGuard AI   -   IEEE AIML-02", styles["Small"]))
    story.append(Spacer(1, 12))

    # ---- Verdict banner ----
    v = verdict.get("verdict", "?")
    score = float(verdict.get("score", 0.0)) * 100.0
    conf  = float(verdict.get("confidence", 0.0)) * 100.0
    color = colors.HexColor("#ef4444") if v == "FAKE" else \
            colors.HexColor("#60a5fa") if v == "NO_FACE" else \
            colors.HexColor("#f59e0b") if v == "INCONCLUSIVE" else \
            colors.HexColor("#10b981")
    icon  = "!" if v == "FAKE" else "?" if v in ("INCONCLUSIVE", "NO_FACE") else "OK"
    label = "MANIPULATION SUSPECTED" if v == "FAKE" else \
            "NO SUITABLE FACE" if v == "NO_FACE" else \
            "INCONCLUSIVE" if v == "INCONCLUSIVE" else "LIKELY AUTHENTIC"

    banner = Table([[f"{icon}   {label}"]], colWidths=[7 * inch])
    banner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), color),
        ("TEXTCOLOR",  (0, 0), (-1, -1), colors.white),
        ("FONTNAME",   (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 20),
        ("ALIGN",      (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
    ]))
    story.append(banner)
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        f"<para align=center><b>Fake probability: {score:.2f}%   -   "
        f"Confidence: {conf:.2f}%   -   Inference: {verdict.get('elapsed_ms', 0):.0f} ms</b></para>",
        styles["Normal"],
    ))
    story.append(Spacer(1, 14))

    # ---- Exhibit info ----
    story.append(Paragraph("Exhibit Information", styles["SubH"]))
    fname = os.path.basename(input_path)
    fsize = os.path.getsize(input_path) if os.path.exists(input_path) else 0
    exhibit_rows = [
        ["Filename",       fname],
        ["File size",      f"{fsize:,} bytes"],
        ["Kind",           verdict.get("kind", "?").upper()],
        ["Analyzed at",    datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S %Z")],
        ["SHA-256",        _wrap(sha256)],
        ["Perceptual hash", phash or "-"],
    ]
    story.append(_kv_table(exhibit_rows, TableStyle, colors))

    # ---- Evidence authentication ----
    evidence = verdict.get("evidence_auth") or {}
    if evidence:
        story.append(Paragraph("Digital Evidence Authentication", styles["SubH"]))
        auth_rows = [
            ["Evidence ID", evidence.get("evidence_id", "unavailable")],
            ["Authenticated analyst", evidence.get("authenticated_user", "unavailable")],
            ["Analyzed at (UTC)", evidence.get("analyzed_at_utc", "unavailable")],
            ["Metadata", "available" if evidence.get("metadata_available") else "limited or absent"],
            ["Modification trace", evidence.get("modification_status", "inconclusive")],
            ["C2PA status", evidence.get("c2pa_status", "not checked")],
        ]
        story.append(_kv_table(auth_rows, TableStyle, colors))
        story.append(Spacer(1, 5))
        story.append(Paragraph(evidence.get("scope_note", ""), styles["Small"]))

    # ---- Model info ----
    story.append(Paragraph("Detection Model", styles["SubH"]))
    model_rows = [
        ["Model",   verdict.get("model_name", "?")],
        ["Version", verdict.get("model_version", "?")],
        ["Verdict", v],
        ["Fake probability", f"{score:.4f}"],
        ["Confidence",       f"{conf:.4f}"],
    ]
    story.append(_kv_table(model_rows, TableStyle, colors))

    # ---- Video timeline ----
    if verdict.get("kind") == "video":
        story.append(Paragraph("Per-Frame Timeline (video)", styles["SubH"]))
        img_bytes = _timeline_png(verdict)
        if img_bytes:
            story.append(RLImage(io.BytesIO(img_bytes), width=6.6 * inch, height=2.2 * inch))
        else:
            story.append(Paragraph("<i>Timeline chart unavailable.</i>", styles["Normal"]))

        tf = verdict.get("top_frames", [])
        if tf:
            story.append(Spacer(1, 8))
            story.append(Paragraph(
                f"Top {len(tf)} most-suspicious sampled frames:", styles["Normal"]))
            top_rows = [["Rank", "Frame index", "Fake score"]]
            for i, f in enumerate(tf, 1):
                top_rows.append([str(i), str(f.get("frame_index", "?")),
                                 f"{float(f.get('score', 0)) * 100:.1f}%"])
            t = Table(top_rows, colWidths=[0.7 * inch, 2 * inch, 2 * inch])
            t.setStyle(TableStyle([
                ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a8a")),
                ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
                ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE",   (0, 0), (-1, -1), 9),
                ("ALIGN",      (0, 0), (-1, -1), "CENTER"),
            ]))
            story.append(t)

    tracks = verdict.get("tracks") or []
    if tracks:
        story.append(Spacer(1, 10))
        story.append(Paragraph("Per-Person Track Results", styles["SubH"]))
        rows = [["Track", "Observations", "Score", "Verdict"]]
        for track in tracks:
            rows.append([str(track.get("face_id", "?")),
                         str(track.get("observations", 0)),
                         f"{float(track.get('score', 0))*100:.1f}%",
                         track.get("verdict", "INCONCLUSIVE")])
        story.append(_kv_table(rows, TableStyle, colors))

    story.append(Spacer(1, 12))
    story.append(Paragraph("Interpretation and Limitations", styles["SubH"]))
    story.append(Paragraph(
        "This automated result is a screening aid, not proof of authenticity or manipulation. "
        "Scores may be unreliable for unseen manipulation methods, heavy compression, blur, "
        "small faces, screenshots, or re-encoded media. EXIF absence and compression anomalies "
        "are supporting indicators only. Preserve the original exhibit and obtain qualified "
        "human forensic review before legal or judicial reliance.", styles["Small"]))
    # ---- Analyst notes ----
    story.append(Spacer(1, 14))
    story.append(Paragraph("Analyst Notes", styles["SubH"]))
    story.append(Paragraph("<i>Space for handwritten annotations, case number, "
                           "and analyst signature below.</i>", styles["Small"]))
    notes = Table([[" "]] * 4, colWidths=[7 * inch])
    notes.setStyle(TableStyle([
        ("BOX",  (0, 0), (-1, -1), 0.5, colors.grey),
        ("LINEBELOW", (0, 0), (-1, -2), 0.4, colors.grey),
        ("ROWHEIGHTS", (0, 0), (-1, -1), 0.4 * inch),
    ]))
    story.append(notes)

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "This report was generated by an automated forensic assistant. "
        "Findings should be reviewed by a qualified digital-forensics analyst "
        "before being used as evidence.",
        styles["Small"],
    ))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def _kv_table(rows, TableStyle, colors):
    from reportlab.lib.units import inch
    from reportlab.platypus import Table
    t = Table(rows, colWidths=[1.7 * inch, 4.8 * inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eef2ff")),
        ("TEXTCOLOR",  (0, 0), (0, -1), colors.HexColor("#1e3a8a")),
        ("FONTNAME",   (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",   (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",   (0, 0), (-1, -1), 9),
        ("VALIGN",     (0, 0), (-1, -1), "TOP"),
        ("GRID",       (0, 0), (-1, -1), 0.3, colors.HexColor("#d1d5db")),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
    ]))
    return t


def _wrap(s, per=48):
    """Insert soft breaks so long hashes don't overflow."""
    return " ".join(s[i:i + per] for i in range(0, len(s), per)) if s else ""


def _footer(canvas, doc):
    from reportlab.lib import colors as rc
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(rc.grey)
    canvas.drawString(0.7 * 72, 0.4 * 72,
                      "DeepGuard AI  -  Digital Evidence Report")
    canvas.drawRightString(8.3 * 72, 0.4 * 72, f"Page {doc.page}")
    canvas.restoreState()


def _timeline_png(verdict: dict) -> bytes | None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
        xs = np.array(verdict.get("frame_indices", []))
        ys = np.array(verdict.get("per_frame", []))
        if len(xs) == 0:
            return None
        fig, ax = plt.subplots(figsize=(6.6, 2.2))
        ax.plot(xs, ys, color="#3b82f6", lw=1.5)
        ax.fill_between(xs, ys, 0.35, where=(ys > 0.35), color="#fca5a5", alpha=0.5)
        ax.fill_between(xs, ys, 0.35, where=(ys <= 0.35), color="#a7f3d0", alpha=0.5)
        ax.axhline(0.35, color="#f59e0b", lw=1.0, ls="--")
        ax.set_ylim(-0.05, 1.05)
        ax.set_xlabel("Frame index"); ax.set_ylabel("Fake prob.")
        ax.set_title(f"Overall screening score: {verdict.get('score', 0)*100:.1f}%")
        fig.tight_layout()
        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=110)
        plt.close(fig)
        return buf.getvalue()
    except Exception:
        return None


def _stub_pdf(msg: str) -> bytes:
    body = (
        b"BT /F1 14 Tf 72 720 Td (Evidence Report) Tj ET\n"
        b"BT /F1 10 Tf 72 690 Td (" + msg.encode("latin-1", "ignore") + b") Tj ET\n"
    )
    return (
        b"%PDF-1.4\n"
        b"1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
        b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
        b"3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R"
        b"/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj\n"
        b"4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n"
        b"5 0 obj<</Length " + str(len(body)).encode() + b">>stream\n" + body +
        b"endstream endobj\n"
        b"xref 0 6 trailer<</Size 6/Root 1 0 R>>startxref 0 %%EOF\n"
    )
